### ISSUE TITLE
invalid regular expression; '{' can't be last character

### ISSUE THREAD

**Issue by Spredzy** [laurilehmijoki/tomcat7_rhel#13]
When running the test suite I get the following error 

```
Library/Ruby/Gems/1.8/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load': /Users/yanisguenane/projects/tomcat7_rhel/spec/defines/tomcat7_rhel__tomcat_application_spec.rb:167: invalid regular expression; '{' can't be last character: /\/opt\/my-web-app\/logs\/\*access_log\*.txt {/ (SyntaxError)
    from /Library/Ruby/Gems/1.8/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'
    from /Library/Ruby/Gems/1.8/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `each'
    from /Library/Ruby/Gems/1.8/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'
    from /Library/Ruby/Gems/1.8/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:22:in `run'
    from /Library/Ruby/Gems/1.8/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
    from /Library/Ruby/Gems/1.8/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `autorun'
    from /Library/Ruby/Gems/1.8/bin/rspec:19
rake aborted!
```

**Comment by laurilehmijoki** [comment]
Thanks for the pull request.
